name: Build frontend

# Controls when the workflow will run
on:
  push:
    paths:
      - 'teslausb-www/frontend/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_VERSION: '12.x'                # set this to the node version to use


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: yarn install, build
        run: |
          cd teslausb-www/frontend
          yarn
          yarn build
          ls -la dist/
          tar -zcvf dist.tar.gz dist
          ls -la

      - name: Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          add: 'teslausb-www/frontend/dist.tar.gz'
          author_name: Github Actions
